name: MapRights
version: '${version}'
main: com.archerwn.mapRights.MapRights
api-version: '1.21'
author: ArcherWn
description: A Minecraft plugin that allows players to sign maps, protecting their creations from unauthorized copying.

softdepend: [ Vault, PlaceholderAPI ]

commands:
  maprights:
    description: Manage map rights.
    usage: /<command> < sign | unsign | resign | forcesign | forceunsign | info >
    aliases: [ mr ]

permissions:
  maprights.*:
    description: Gives access to all MapRights commands.
    children:
      maprights.sign: true
      maprights.unsign: true
      maprights.resign: true
      maprights.forcesign: true
      maprights.forceunsign: true
      maprights.info: true

  maprights.sign:
    description: Allows players to sign maps.
    default: true
  maprights.unsign:
    description: Allows players to unsign maps.
    default: true
  maprights.resign:
    description: Allows players to resign maps.
    default: true
  maprights.forcesign:
    description: Allows players to forcefully sign maps.
    default: op
  maprights.forceunsign:
    description: Allows players to forcefully unsign maps.
    default: op
  maprights.info:
    description: Allows players to view map information.
    default: op


